version: '3.8'

services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

# volumes:
#   db_data:


networks:
  app-network:
    driver: bridge
